Mission7-Higbee/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Mission7_Higbee.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission7_Higbee.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository Repo { get; set; }
        private Cart Cart { get; set; }
    
        public PurchaseController(IPurchaseRepository temp, Cart c)
        {
            Repo = temp;
            Cart = c;
        }
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if(Cart.Items.Count()==0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty");
            }
            if (ModelState.IsValid)
            {
                purchase.Lines = Cart.Items.ToArray();
                Repo.SavePurchase(purchase);
                Cart.ClearCart();

                return RedirectToPage("/Confirmation");
            }
            else
            {
                return View();
            }
        }
    }
}

Mission7-Higbee/Pages/Confirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Mission7_Higbee.Pages
{
    public class ConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Mission7-Higbee/Pages/Shop.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission7_Higbee.Infrastructure;
using Mission7_Higbee.Models;

namespace Mission7_Higbee.Pages
{
    public class ShopModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public ShopModel (IBookstoreRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }
        public Cart cart { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(b => b.BookId == bookId);

            cart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            cart.RemoveItem(cart.Items.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new {ReturnUrl = returnUrl });
        }
    }
}

Mission7-Higbee/Pages/Confirmation.cshtml
@page
@model Mission7_Higbee.Pages.ConfirmationModel
@{
}

<div class="text-center">
    <h3>Thank you for your order! Your package is on the way!</h3>
    <a class="btn btn-primary" asp-controller="Home">Return to Home</a>
</div>

Mission7-Higbee/Pages/Shop.cshtml
@page
@model Mission7_Higbee.Pages.ShopModel
@{
}

<h2>Your Cart:</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach(var i in Model.cart.Items)
            {
                <tr>
                    <td>@i.Book.Title</td>
                    <td>@i.Quantity</td>
                    <td>@((i.Book.Price).ToString("c"))</td>
                    <td>@((i.Quantity*i.Book.Price).ToString("c"))</td>

                    <td class="text-center">
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="bookId" value="@i.Book.BookId" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                        </form>
                </tr>
            }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>

</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
</div>

Mission7-Higbee/Pages/_ShopLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <!--Creates div for the toolbar at top of page-->
        <span class="navbar-brand ml-2">The Bookstore</span> <!--Text in the toolbar-->
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>