Mission7-Higbee/Components/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mission7_Higbee.Models;

namespace Mission7_Higbee.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }
        public CategoryViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.Category = RouteData?.Values["bookCategory"];

            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

Mission7-Higbee/Views/Shared/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission7_Higbee.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission7_Higbee.Views.Shared.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }

}

Mission7-Higbee/Views/Shared/BookSummary.cshtml
@model Book

<div class="card p-2">
    <h3 class="card-header">@Model.Title</h3>
    <span class="badge bg-info" style="float:right">  </span>
    <div class="card-body">
        <p class="card-text">Author: @Model.Author</p>
        <p class="card-text">Publisher: @Model.Publisher</p>
        <p class="card-text">ISBN: @Model.Isbn</p>
        <p class="card-text">Classification: @Model.Classification</p>
        <p class="card-text">Category: @Model.Category</p>
        <p class="card-text">Page Count: @Model.PageCount</p>
   
        <form method="post" asp-page="/Shop">

            <input type="hidden" asp-for="@Model.BookId" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text">
                <button type="submit" class="btn btn-success btn-sm">Buy- $@Model.Price</button>
            </span>
        </form>
    </div>
</div>
<br />

Mission7-Higbee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title> <!--Where to display the title-->
    <link href="~/lib/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/fontawesome-free-5.15.4-web/css/all.min.css" rel="stylesheet" />

</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">The Bookstore</div>
                <div class="col-3 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:category></vc:category>
        </div>

        <div class="col-9">
            @RenderBody() <!--Where to render each specific page's information-->
        </div>
    </div>

</body>
</html>